name: dfc_llama
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage: "https://github.com/sgehrman/dfc_llama"

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
